apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-back
  namespace: app  # 네임스페이스 설정
  labels:
    app: shop-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-back  
  strategy:
    type: Recreate #pod삭제시 새파드 생성
  template:
    metadata:
      labels:
        app: shop-back
    spec:
      containers:
        - name: shop-back
          image: cloudbreak6th/shop-back:v1.0
          env:
           - name: SPRING_PROFILES_ACTIVE
             value: docker
          ports:
            - containerPort: 8080  # 포트를 80으로 변경
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shop-back
  namespace: app  # 네임스페이스 설정
  labels:
    app: shop-back
spec:
  ports:
    - name: "http"
      port: 80  # 외부에서 노출할 포트
      targetPort: 8080 #컨테이너 내에서 사용하는 포트
  selector:
    app: shop-back

