apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-api
    #namespace: test
  labels:
    app: coupon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-api
  template:
    metadata:
      labels:
        app: coupon-api
    spec:
      containers:
        - name: coupon-api
          image: cloudbreak6th/coupon-api:v2.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_HOST
              value: coupon-mysql 
            - name: MYSQL_PORT
              value: "3306"
            - name: DATASOURCE_URL
              value: jdbc:mysql://coupon-mysql:3306/coupon
            - name: MYSQL_DATABASE
              value: coupon
            - name: MYSQL_USER
              value: abcd
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: REDIS_HOST
              value: coupon-redis
            - name: REDIS_PORT
              value: "6379"
            - name: PROFILES_ACTIVE
              value: docker
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: coupon-api
    #namespace: test
  labels:
    app: coupon-api
spec:
  selector:
   app: coupon-api
  ports:      
    - name: coupon-api
      port: 8080
      targetPort: 8080
